arct_man/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(TemplateView.as_view(template_name='main.html')), name='main'),
    path('users/', include('users.urls')),
    path('cargo_spec/', include('cargo_spec.urls')),
    path('report/', include('report.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cargo_spec/urls.py
from django.urls import path

from cargo_spec.views import MyListView, AddSpecificationView, ModifySpecificationView, DeleteSpecificationView, SpecificationDetailView, SpecificationScanUploadView, SpecificationPhotoUploadView, DeleteSpecificationDocumentView, SpecificationPDFView, ApprovedSpecificationsView, SpecificationCsvView

app_name = 'cargo_spec'
urlpatterns = [
    path('', MyListView.as_view(), name='my-lists'),
    path('specification/add', AddSpecificationView.as_view(), name='add-spec'),
    path('specification/<int:pk>/modify', ModifySpecificationView.as_view(), name='modify-spec'),
    path('specification/<int:pk>/delete', DeleteSpecificationView.as_view(), name='delete-spec'),
    path('specification/<int:pk>/detail', SpecificationDetailView.as_view(), name='spec-detail'),
    path('specification/<int:pk>/upload_scan', SpecificationScanUploadView.as_view(), name='scan-upload'),
    path('specification/<int:pk>/upload_photo', SpecificationPhotoUploadView.as_view(), name='photo-upload'),
    path('specification/<int:spk>/doc/<int:pk>/delete', DeleteSpecificationDocumentView.as_view(), name='delete-doc'),
    path('specification/<int:pk>/pdf', SpecificationPDFView.as_view(), name='spec-pdf'),
    path('specifications', ApprovedSpecificationsView.as_view(), name='approved-spec'),
    path('specifications/csv', SpecificationCsvView.as_view(), name='spec-csv'),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from users.views import Login, SignUp, Logout

app_name = 'users'
urlpatterns = [
    path('signup/',SignUp.as_view(), name = 'signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/',Logout.as_view(), name='logout')
]

cargo_spec/models.py
import os
from django.contrib import admin

from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator

class Specification(models.Model):
    STORAGE = (
        ('POKŁAD', 'pokład'),
        ('ŁADOWNIA', 'ładownia'),
        ('KABINA', 'kabina'),
        ('+4', '+4'), 
        ('-20', '-20'),
        ('-80', '-80'),
        ('DOWOLNE', 'dowolne')
)

    marking = models.CharField(unique=True, max_length=64)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    package_type = models.CharField(max_length=64)
    dimension_length = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    dimension_width = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    dimension_height = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    capacity = models.PositiveIntegerField()
    weight =  models.PositiveIntegerField(validators=[MinValueValidator(1)])
    storage = models.CharField(max_length=32, choices=STORAGE)
    description = models.CharField(max_length=128)
    total_value = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    approved = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        capacity_ = self.dimension_length * self.dimension_width * self.dimension_height
        self.capacity = capacity_
        
        super().save(*args, **kwargs)

    def __str__(self):
        return self.marking


class CargoContent(models.Model):
    name = models.CharField(max_length=128, verbose_name='Nazwa')
    serial_number = models.CharField(max_length=64, blank=True, verbose_name='Nr seryjny**')
    quantity = models.DecimalField(max_digits=7, decimal_places=1, verbose_name='Ilość')
    unit_of_measurement = models.CharField(max_length=24, verbose_name='Jedn. miary')
    value = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Wartość (PLN)')
    specification = models.ForeignKey(Specification, on_delete=models.CASCADE, related_name='cargos_content')
    
    def __str__(self):
        return f'{self.specification.marking} - {self.name}'
    

def get_upload_path(instance, filename, *args, **kwargs):
    try:
        if instance.file_type == 'scan-upload':
            txt = 'scan'
    except Exception:
        txt = 'photo'
    name = f'{instance.specification.marking}_{txt}_{filename}'
    path = f'cargo_spec/{instance.specification.marking}/{txt}'
    return os.path.join(path, name)

class SpecificationDocument(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to=get_upload_path)
    uploaded_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    specification = models.ForeignKey(Specification, on_delete=models.CASCADE)
    
    @property
    def filename(self):
        return os.path.basename(self.document.name)

    @property
    def only_file_path(self):
        return os.path.dirname(self.document.name)

    @property
    def pdf_extension(self):
        document = self.document.name
        if document.endswith('.pdf'):
            return True

cargo_spec/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from django.urls import resolve, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_weasyprint import WeasyTemplateResponseMixin

from cargo_spec.forms import (
    CargoContentFormSet,
    MultipleSpecificationDocumentForm,
    SingleSpecificationDocumentForm,
    SpecificationForm,
)
from cargo_spec.models import CargoContent, Specification, SpecificationDocument
from cargo_spec.tables import CargoContentTable
from cargo_spec.resources import SpecificationResource
from cargo_spec.utils import check_scan_file, specification_marking


def user_test(self):
    self.object = self.get_object()
    pass_test = [self.request.user.is_staff, self.request.user == self.object.owner]
    return any(pass_test)


class MyListView(LoginRequiredMixin, ListView):
    model = Specification
    template_name = "cargo_spec/my_lists.html"
    ordering = ["-marking"]

    def get_queryset(self):
        queryset = super().get_queryset()
        owner_ = self.request.user
        return queryset.filter(owner=owner_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context["a_list"] = [s.approved for s in queryset]
        return context


class AddSpecificationView(LoginRequiredMixin, CreateView):
    model = Specification
    template_name = "cargo_spec/specification_form.html"
    form_class = SpecificationForm

    def get_context_data(self, **kwargs):
        data = super(AddSpecificationView, self).get_context_data(**kwargs)
        if self.request.POST:
            data["cargos"] = CargoContentFormSet(self.request.POST)
        else:
            data["cargos"] = CargoContentFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        cargos = context["cargos"]
        with transaction.atomic():
            form.instance.owner = self.request.user
            form.instance.marking = specification_marking(form)

            self.object = form.save()

            # Sprawdza czy wszystkie wymagane pola dla modelu CargoContent są wypełnione, jeśli nie, to zwraca formularz
            if cargos.is_valid():
                cargos.instance = self.object
                cargos.save()
            else:
                return self.render_to_response(
                    self.get_context_data(form=form, cargos=cargos)
                )

        return super(AddSpecificationView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("cargo_spec:my-lists")


class ModifySpecificationView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Specification
    template_name = "cargo_spec/specification_form.html"
    form_class = SpecificationForm

    def test_func(self):
        return user_test(self)

    def get_context_data(self, **kwargs):
        data = super(ModifySpecificationView, self).get_context_data(**kwargs)

        if self.object.approved is True:
            raise PermissionDenied()

        if self.request.POST:
            data["cargos"] = CargoContentFormSet(
                self.request.POST, instance=self.object
            )
        else:
            data["cargos"] = CargoContentFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        cargos = context["cargos"]
        with transaction.atomic():

            if "accept_spec" in self.request.POST:
                form.instance.approved = True

            self.object = form.save()

            if cargos.is_valid():
                cargos.instance = self.object
                cargos.save()
            else:
                return self.render_to_response(
                    self.get_context_data(form=form, cargos=cargos)
                )

        return super(ModifySpecificationView, self).form_valid(form)

    def get_success_url(self):
        if self.object.approved is False:
            return reverse_lazy("cargo_spec:my-lists")
        else:
            # FIXME: zrobić przekierowanie do cargo_spec:spec-detail
            return reverse_lazy("cargo_spec:my-lists")


class DeleteSpecificationView(LoginRequiredMixin, DeleteView):
    model = Specification

    def get_success_url(self):
        return reverse_lazy("cargo_spec:my-lists")


# TODO: sprawdzić czy potrzebny jest login i user passes


class SpecificationDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Specification
    template_name = "cargo_spec/specification_detail.html"
    # NOTE: uzyskujemy dzięki temu zmianę w template z {{object}} na {{specification}}
    context_object_name = "specification"

    def test_func(self):
        return user_test(self)

    def get(self, request, *args, **kwargs):
        data = super(SpecificationDetailView, self).get(request, *args, **kwargs)
        if self.object.approved is False:
            raise PermissionDenied()
        return data

    def get_context_data(self, **kwargs):
        context = super(SpecificationDetailView, self).get_context_data(**kwargs)
        specification_ = get_object_or_404(Specification, pk=self.kwargs["pk"])
        table = CargoContentTable(
            CargoContent.objects.filter(specification=specification_)
        )
        context["table"] = table
        return context


class SpecificationScanUploadView(LoginRequiredMixin, View):
    template_name = "cargo_spec/file_upload.html"
    form_class = SingleSpecificationDocumentForm

    def get(self, request, *args, **kwargs):
        spec = Specification.objects.get(pk=self.kwargs["pk"])
        if (spec.owner != self.request.user) or (check_scan_file(spec.marking)):
            raise PermissionDenied()
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            spec = get_object_or_404(Specification, pk=self.kwargs["pk"])
            form.instance.file_type = resolve(request.path_info).url_name
            form.instance.specification = spec
            owner = self.request.user
            form.instance.uploaded_by = owner
            form.save()
            return redirect("cargo_spec:spec-detail", spec.pk)
        else:
            return render(request, self.template_name, {"form": form})


class SpecificationPhotoUploadView(LoginRequiredMixin, View):
    template_name = "cargo_spec/file_upload.html"
    form_class = MultipleSpecificationDocumentForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        files = request.FILES.getlist("file_field")
        if form.is_valid():
            spec = get_object_or_404(Specification, pk=self.kwargs["pk"])
            owner = self.request.user
            for doc in files:
                SpecificationDocument.objects.create(
                    description=form.cleaned_data["description"],
                    document=doc,
                    uploaded_by=owner,
                    specification=spec,
                )
            return redirect("cargo_spec:spec-detail", self.kwargs["pk"])
        else:
            return render(request, self.template_name, {"form": form})


class DeleteSpecificationDocumentView(LoginRequiredMixin, DeleteView):
    model = SpecificationDocument

    def get_success_url(self):
        spk = self.kwargs["spk"]
        return reverse_lazy("cargo_spec:spec-detail", kwargs={"pk": spk})


class SpecificationPDFView(LoginRequiredMixin, WeasyTemplateResponseMixin, DetailView):
    model = Specification
    template_name = "cargo_spec/specification_to_pdf.html"
    context_object_name = "specification"
    # pdf_attachment = False
    pdf_stylesheets = [
        "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    ]

    def get(self, request, *args, **kwargs):
        context = super(SpecificationPDFView, self).get(request, *args, **kwargs)
        if (self.object.owner != self.request.user) or (self.object.approved is False):
            raise PermissionDenied()
        return context

    def get_context_data(self, **kwargs):
        context = super(SpecificationPDFView, self).get_context_data(**kwargs)
        specification_ = get_object_or_404(Specification, pk=self.kwargs["pk"])
        empty_row_len = range(20 - specification_.cargos_content.all().count())
        context["empty_row_len"] = empty_row_len
        return context

    def get_pdf_filename(self):
        specification_ = get_object_or_404(Specification, pk=self.kwargs["pk"])
        pdf_filename = f"{specification_.marking}.pdf"
        return pdf_filename


class ApprovedSpecificationsView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Specification
    template_name = "cargo_spec/approved_specifications.html"
    ordering = ["owner_id"]

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(approved=True)


class SpecificationCsvView(View):
    def get(self, *args, **kwargs):
        dataset = SpecificationResource().export()
        response = HttpResponse(dataset.csv, content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="specifications.csv"'
        return response

templates/cargo_spec/approved_specifications.html
{% extends "base.html" %}

{% block content %}
<h3>Zatwierdzone specyfikacje ładunkowe:</h3>
{% if not object_list %}
    <p>Brak list</p>
{% else %}
    <ul>
        {% for object in object_list %}
                <li><a href="{% url 'cargo_spec:spec-detail' object.id %}">{{ object.marking }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

<a href="{% url 'cargo_spec:spec-csv' %}">Pobierz plik CSV</a>
{% endblock %}

templates/cargo_spec/file_upload.html
{% extends 'base.html' %}
{% block content %}
{% if 'scan' in request.path %}
<h2>Wgraj plik ze skanem podpisanej specyfikacji</h2>
{% else %}
<h2>Wgraj zdjęcie/zdjęcia paczki</h2>
{% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
{% endblock %}

templates/cargo_spec/my_lists.html
{% extends "base.html" %}

{% block content %}
<h3>Specyfikacje ładunkowe:</h3>
{% if not object_list %}
    <p>Brak list</p>
{% else %}
    {% if True in a_list %}
        <p>Zatwierdzone</p>
        <ul>
        {% for object in object_list %}
            {% if object.approved %}
                <li><a href="{% url 'cargo_spec:spec-detail' object.id %}">{{ object.marking }}</a></li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}
    {% if False in a_list %}
        <p>Niezatwierdzone</p>
        <ul>
        {% for object in object_list %}
            {% if not object.approved %}
                <li><a href="{% url 'cargo_spec:modify-spec' object.id %}">{{ object.marking }}</a></li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}
{% endif %}

<a href="{% url 'cargo_spec:add-spec' %}">Dodaj specyfikację</a>
{% endblock %}

templates/cargo_spec/specification_detail.html
{% extends "base.html" %}
{% block content %}
{% load upload_extras %}
{% load render_table from django_tables2 %}


{% comment %} height: auto; {% endcomment %}
<style>
img {
    width: 100px;
    height: auto;
}
.icon {
    font-size: 100px;
}
</style>


<div class="container">
<div class="mx-auto col-10">
<div class="card">
<div class="card-header"><center><h3>Specyfikacja ładunkowa: {{ specification.marking }}</h3></center></div>
<div class="row justify-content-center">
<a href="{% url 'cargo_spec:spec-pdf' specification.id %}" class="btn btn-success">Pobierz PDF</a>
</div>
</div>
</div>
</div>

<div class="container">
    <div class="mx-auto col-10">
        <dl class="row col-9 mx-auto mt-4">
            <dt class="col-6 mb-3">Rodzaj opakowania</dt>
            <dd class="col-6 text-right mb-3">{{ specification.package_type }}</dt>
            <dt class="col-6 mb-3">Wymiary w cm [dł/szer/wys]</dt>
            <dd class="col-6 text-right mb-3">{{ specification.dimension_length }}x{{ specification.dimension_width }}x{{ specification.dimension_height }}</dt>
            <dt class="col-6 mb-3">Waga w kg</dt>
            <dd class="col-6 text-right mb-3">{{ specification.weight }}</dt>
            <dt class="col-6 mb-4">Warunki przechowywania</dt>
            <dd class="col-6 text-right mb-4">{{ specification.storage }}</dt>
        </dl>
<hr />
</div>
</div>

<div class="container">
    <div class="mx-auto col-10">
{% render_table table %}
</div>
    <div class="mx-auto col-10">
<div class="text-right mb-5"><strong>Łączna wartość: {{ specification.total_value }}</strong></div>
</div>
</div>

{% if specification.specificationdocument_set.all %}
<div class="container">
    <div class="mx-auto col-10">
<hr />
<div class="card">
<center><h4>Wgrane pliki:</h4></center>
</div>
</div>
<div class="mx-auto col-8">
<ul class="list-unstyled mt-3">
    {% for doc in specification.specificationdocument_set.all|sort_docs %}
        {% if '/scan' in doc.only_file_path %}
        <li class="media">
            {% if doc.pdf_extension %}
            <div class='icon'><i class="far fa-file-pdf align-self-center fa-fw"></i></div>
            {% else %}
            <img src="{{ doc.document.url}}" class="align-self-center mr-3">
            {% endif %}
        <div class="media-body">
        <p class="mt-3">Skan: <a href="{{ doc.document.url}}">{{ doc.filename }}</a>
            <form action="{% url 'cargo_spec:delete-doc' specification.id doc.id %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="hidden" name="doc.id" value="{{ doc.pk }}">
                <button type="submit" class="btn btn-danger" onclick='return confirm("Czy napewno usunąć plik {{ doc.filename }}?");'>Usuń</button>
            </form>
        </p>
        </div>
        </li>
        <hr />
        {% else %}
        <li class="media">
        <img src="{{ doc.document.url}}" class="align-self-center mr-3">
        <div class="media-body">
        <p class="mt-3">Zdjęcie: <a href="{{ doc.document.url}}">{{ doc.filename }}</a>
            <form action="{% url 'cargo_spec:delete-doc' specification.id doc.id %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="hidden" name="doc.id" value="{{ doc.pk }}">
                <button type="submit" class="btn btn-danger" onclick='return confirm("Czy napewno usunąć plik {{ doc.filename }}?");'>Usuń</button>
            </form>
        </p>
        </div>
        </li>
        <hr />
        {% endif %}
    {% endfor %}
</ul>
</p>
</div>
{% endif %}

<div class="container">
    <div class="mx-auto col-10 mb-5">
<div class="row">
{% if not specification.marking|check_scan_file %}
<div class="col-6 mx-auto">
<form action="{% url 'cargo_spec:scan-upload' specification.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="specification_id" value="{{ specification.id }}" />
        <button type="submit" class="btn btn-info">Upload skanu</button>
</form>
</div>
{% endif %}
<div class="col-6">
<form action="{% url 'cargo_spec:photo-upload' specification.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="specification_id" value="{{ specification.id }}" />
{% if not specification.marking|check_scan_file %}
        <div class="text-right">
        {% endif %}
        <button type="submit" class="btn btn-info">Upload zdjęć</button>
        </div>
</div>
</form>
</div>
</div>
</div>
{% endblock %}

templates/cargo_spec/specification_form.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>

{% comment %} .asteriskField usuwa "*" przy obowiązkowych polach formularza, właściwość crispy-forms{% endcomment %}
<style>
    .asteriskField {
        display: none;
    }

    body {
        background-image: linear-gradient(to top, #e6e9f0 0%, #eef1f5 100%);
    }
</style>

{% url 'cargo_spec:add-spec' as add_url %}
{% url 'cargo_spec:modify-spec' specification.id as modify_url %}

<div class='container'>
    <div class="mx-auto col-10">
        <div class='card'>
            {% if request.get_full_path == add_url %}
            <div class='card-header'>
                <center>
                    <h3>Dodaj specyfikację: {{ specification.marking }}</h3>
                </center>
            </div>
            {% else %}
            <div class='card-header'>
                <center>
                    <h3>Specyfikacja ładunkowa: {{ specification.marking }}</h3>
                </center>
                <form action="{% url 'cargo_spec:delete-spec' specification.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="specification_id" value="{{ specification.id }}" />
                    <center>
                        <button type="submit" class='btn btn-danger'
                            onclick='return confirm("Czy napewno usunąć specyfikację {{ specification.marking }}?");'>Usuń
                            całą specyfikację</button>
                    </center>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="container">
    <div class="mx-auto col-10">
        <form action="" method="POST">{% csrf_token %}
            {% comment %} {{ form|crispy }} {% endcomment %}
            <div class='form-row'>
                <div class='form-group col mb-0'>
                    {{ form.package_type|as_crispy_field }}
                </div>
                <div class='form-group col mb-0'>
                    {{ form.storage|as_crispy_field }}
                </div>
            </div>
            <div class='form-row'>
                <div class='form-group col mb-0'>
                    {{ form.dimension_length|as_crispy_field }}
                </div>
                <div class='form-group col mb-0'>
                    {{ form.dimension_width|as_crispy_field }}
                </div>
                <div class='form-group col mb-0'>
                    {{ form.dimension_height|as_crispy_field }}
                </div>
                <div class='form-group col mb-0'>
                    {{ form.weight|as_crispy_field }}
                </div>
            </div>
            {{ form.description|as_crispy_field }}
            <div class='form-row'>
                <div class='form-group col-3 mb-0 mx-auto'>
                    {{ form.total_value|as_crispy_field }}
                </div>
            </div>
            <hr />
            <table>
                {{ cargos.management_form|crispy }}

                {% for form in cargos.forms %}
                {% if forloop.first %}
                <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                        {% if field.label != 'Delete' %}
                        <th>{{ field.label|capfirst }}</th>
                        {% endif %}
                        {% endfor %}
                    </tr>
                </thead>
                {% endif %}
                <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                    {% for field in form.visible_fields %}
                    <td>
                        {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% endif %}
                        {{ field.errors.as_ul }}
                        {{ field|as_crispy_field }}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
            <input id="save_spec" type="submit" class="btn btn-primary" value="Zapisz" />
    </div>
    {% if request.get_full_path == modify_url %}
    <div class='container'>
        <div class="mx-auto col-10">
            <div class='card-footer'>
                <center>
                    <input id="accept_spec" type="submit" name="accept_spec" class="btn btn-success"
                    value="Zatwierdź specyfikację" />
                </center>
            </div>
        </div>
    </div>
    {% endif %}
    </form>
</div>

<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'Dodaj kolejny',
        addCssClass: 'add-row btn btn-secondary',
        deleteText: 'Usuń',
        deleteCssClass: 'delete-row btn btn-warning',
        prefix: 'cargos_content',
        added: $('input[name^="cargos_content"][name$="value"]').addClass("value"),
    });
</script>
{% endblock %}