arct_man/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(TemplateView.as_view(template_name='main.html')), name='main'),
    path('users/', include('users.urls')),
    path('cargo_spec/', include('cargo_spec.urls')),
    path('report/', include('report.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cargo_spec/urls.py
from django.urls import path

from cargo_spec.views import MyListView, AddSpecificationView, ModifySpecificationView, DeleteSpecificationView, SpecificationDetailView, SpecificationScanUploadView, SpecificationPhotoUploadView, DeleteSpecificationDocumentView, SpecificationPDFView, ApprovedSpecificationsView, SpecificationCsvView

app_name = 'cargo_spec'
urlpatterns = [
    path('', MyListView.as_view(), name='my-lists'),
    path('specification/add', AddSpecificationView.as_view(), name='add-spec'),
    path('specification/<int:pk>/modify', ModifySpecificationView.as_view(), name='modify-spec'),
    path('specification/<int:pk>/delete', DeleteSpecificationView.as_view(), name='delete-spec'),
    path('specification/<int:pk>/detail', SpecificationDetailView.as_view(), name='spec-detail'),
    path('specification/<int:pk>/upload_scan', SpecificationScanUploadView.as_view(), name='scan-upload'),
    path('specification/<int:pk>/upload_photo', SpecificationPhotoUploadView.as_view(), name='photo-upload'),
    path('specification/<int:spk>/doc/<int:pk>/delete', DeleteSpecificationDocumentView.as_view(), name='delete-doc'),
    path('specification/<int:pk>/pdf', SpecificationPDFView.as_view(), name='spec-pdf'),
    path('specifications', ApprovedSpecificationsView.as_view(), name='approved-spec'),
    path('specifications/csv', SpecificationCsvView.as_view(), name='spec-csv'),
]

report/urls.py
from django.urls import path

from report.views import ReportContentView, NoteView, AddSectionView

app_name = 'report'
urlpatterns = [
    path('', ReportContentView.as_view(), name='contents-page'),
    path('subsection/<int:pk>', NoteView.as_view(), name='note-list'),
    path('add_section', AddSectionView.as_view(), name='add-section'),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from users.views import Login, SignUp, Logout

app_name = 'users'
urlpatterns = [
    path('signup/',SignUp.as_view(), name = 'signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/',Logout.as_view(), name='logout')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <link href="{% static 'font_awesome/css/all.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% include "navbar.html" %}

    <div style="padding-top: 85px">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

templates/main.html
{% load static %}
<!doctype html>

<html lang="pl">

<head>
    <meta charset="utf-8">

    <title>Sprawozdania i ewidencje skrzyń</title>
    <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</head>

<body>
    <style>
        .jumbotron {
            background-image: url("{% static 'images/Henryk_Arctowski_Polish_Antarctic_Station.jpg' %}");
        }
    </style>

    <header>
        {% include "navbar.html" %}
    </header>

    <main role="main" style="padding-top: 70px">
        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Witaj</h1>
                <p class="lead text-muted">System został stworzony w celu generowania sprawozdań miesięcznych ze stacji
                    oraz ewidencji skrzyń transportowych</p>

            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img src="{% static 'images/document.svg' %}" alt="Sprawozdanie miesięczne" width="100%">
                            <div class="card-body">
                                <p class="card-text">Sekcja umożliwia uzupełnianie i generowanie raportu miesięcznego
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-outline-secondary"
                                            href="{% url 'report:contents-page' %}">Otwórz</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img src="{% static 'images/package.svg' %}" alt="Skrzynie" width="100%">
                            <div class="card-body">
                                <p class="card-text">Sekcja odpowiada za uzupełnianie deklaracji załadunkowych skrzyń
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-outline-secondary"
                                            href="{% url 'cargo_spec:my-lists' %}">Otwórz</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>
            </div>
        </div>

    </main>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Powrót na górę</a>
            </p>
        </div>
    </footer>
</body>

</html>

templates/navbar.html
{% load static %}

<style>
    .navbar {
        padding-top: 0;
        padding-bottom: 0;
    }

    .nav-item {
        padding-top: 15px;
        padding-bottom: 15px;
        border-radius: 0;
    }

    .active-back {
        background: #afb078;
    }
</style>

{% url 'cargo_spec:approved-spec' as approved_url %}
{% url 'main' as main_url %}

<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main'%}"><img src="{% static 'images/logo_arct_pl.jpg' %}"
            style="width: 50px; margin-right: 10px;">{% if request.get_full_path == main_url %}System Obsługi Stacji
        Arctowski{% else %}Arctowski{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if request.get_full_path != main_url %}
                <li class="nav-item {% if appname == 'report' %}active active-back{% endif %}">
                    <a class="nav-link" href="{% url 'report:contents-page' %}">Raporty</a>
                </li>
                <li class="nav-item {% if appname == 'cargo_spec' %}active active-back{% endif %}">
                    <a class="nav-link" href="{% url 'cargo_spec:my-lists' %}">Specyfikacje</a>
                </li>
                {% if request.user.is_staff %}
                <li id="approved_spec"
                    class="nav-item {% if request.get_full_path == approved_url %}active active-back{% endif %}">
                    <a class="nav-link" href="{% url 'cargo_spec:approved-spec' %}">Specyfikacje pracowników</a>
                </li>
                {% endif %}
            {% endif %}
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout'%}">Wyloguj</a>
            </li>
        </ul>
    </div>
</nav>

<script type="text/javascript">
    $(function () {
        if ($('#approved_spec').hasClass('active')) {
            $('#approved_spec').siblings().removeClass('active active-back');
        };
    });
</script>