arct_man/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(TemplateView.as_view(template_name='main.html')), name='main'),
    path('users/', include('users.urls')),
    path('cargo_spec/', include('cargo_spec.urls')),
    path('report/', include('report.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path

from report.views import ReportContentView, NoteView, AddSectionView

app_name = 'report'
urlpatterns = [
    path('', ReportContentView.as_view(), name='contents-page'),
    path('subsection/<int:pk>', NoteView.as_view(), name='note-list'),
    path('add_section', AddSectionView.as_view(), name='add-section'),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from users.views import Login, SignUp, Logout

app_name = 'users'
urlpatterns = [
    path('signup/',SignUp.as_view(), name = 'signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/',Logout.as_view(), name='logout')
]

report/models.py
from django.db import models
from django.template.loader import render_to_string
from datetime import datetime


class Report(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    
    class Meta:
        unique_together = ['year', 'month']
        
    def save(self, *args, **kwargs):
        self.year = datetime.now().year
        self.month = datetime.now().month
        super().save(*args, **kwargs)
        
    def get_as_html(self):
        return render_to_string('report/report.html', {'report': self})

    def main_sections(self):
        return self.sections.filter(section_master=None)
        
    def __str__(self):
        return f'Sprawozdanie miesięczne ({self.year}-{self.month})'
    

class Section(models.Model):
    title = models.CharField(max_length=128, unique=True)
    text_entry = models.CharField(max_length=128, blank=True)
    text_end = models.CharField(max_length=128, blank=True)
    section_master = models.ForeignKey('self', related_name='subsections', on_delete=models.CASCADE, blank=True, null=True)
    report = models.ForeignKey(Report, related_name='sections', on_delete=models.CASCADE, blank=True, null=True)
    
    class Meta:
        ordering = ['pk']
    
    def __str__(self):
        if self.section_master:
            return f'{self.report.year}/{self.report.month} - {self.section_master.title} - {self.title}'
        return f'{self.report.year}/{self.report.month} - {self.title}'

class Note(models.Model):
    title = models.CharField(max_length=128)
    section = models.ForeignKey(Section, related_name='notes', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.section} - Wpis_id:{self.pk}'

report/forms.py
from django import forms

from report.models import Report, Section, Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title']
        labels = {'title': 'Wpis'}
        

class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ['section_master', 'title', 'text_entry', 'text_end']
        labels = {
            'title': 'Nazwa',
            'text_entry': 'Tekst początkowy',
            'text_end': 'Tekst końcowy',
            'section_master': 'Sekcja główna'
        }

report/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction


from datetime import datetime


from report.models import Report, Section, Note
from report.forms import NoteForm, SectionForm


class ReportContentView(LoginRequiredMixin, DetailView):
    template_name = 'report/report_contents_page.html'

    def get_object(self):
        year_ = datetime.now().year
        month_ = datetime.now().month
        return get_object_or_404(Report, year=year_, month=month_)


class NoteView(LoginRequiredMixin, CreateView):
    form_class = NoteForm
    template_name = 'report/notes.html'

    def get_context_data(self, **kwargs):
        data = super(NoteView, self).get_context_data(**kwargs)
        section_ = get_object_or_404(Section, pk=self.kwargs.get('pk'))
        data['section'] = section_
        data['note_list'] = Note.objects.filter(section=section_).order_by('pk')
        return data
        
    def form_valid(self, form):
        context = self.get_context_data()
        section = context['section']
        with transaction.atomic():
            form.instance.section = section
            self.object = form.save()
        return super(NoteView, self).form_valid(form)
        
    def get_success_url(self):
        context = self.get_context_data()
        section = context['section']
        return reverse_lazy('report:note-list', kwargs={'pk': section.pk})


class AddSectionView(CreateView):
    form_class = SectionForm
    template_name = 'report/add_section.html'
    
    def get_context_data(self, **kwargs):
        data = super(AddSectionView, self).get_context_data(**kwargs)
        year_ = datetime.now().year
        month_ = datetime.now().month
        data['report'] = get_object_or_404(Report, year=year_, month=month_)
        return data

    def get_form(self, *args, **kwargs):
        form = super(AddSectionView, self).get_form(*args, **kwargs)
        # FIXME: musi być lepszy sposób na pobranie raportu, z get_context_data nie działa
        year_ = datetime.now().year
        month_ = datetime.now().month
        report = get_object_or_404(Report, year=year_, month=month_)
        form.fields['section_master'].queryset = report.main_sections()
        return form
        
    def form_valid(self, form):
        context = self.get_context_data()
        report = context['report']
        with transaction.atomic():
            form.instance.report = report
            self.object = form.save()
        return super(AddSectionView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('report:contents-page')

templates/report/add_section.html
{% extends 'base.html' %}
{% block content %}
<h2>Utwórz kategorię</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Potwierdź</button>
  </form>
{% endblock %}

templates/report/notes.html
{% extends "base.html" %}
{% block content %}

<div class=''>
    {% if section.section_master %}
        <h1>{{ section.section_master.title }} - {{ section.title }}</h1>
    {% else %}
        <h1>{{ section.title }}</h1>
    {% endif %}
</div>
<div class=''>
    <ol>
        {% for subsection in section.subsections.all %}
            <li>{% include 'report/sections.html' with section=subsection %}</li>
        {% endfor %}
    </ol>
</div>
<div class=''>
    {{ section.text_entry }}
</div>
{% if note_list %}
    <div class=''>
        <h2>Wpisy:</h2>
        <ul>
            {% for note in note_list %}
                <li>{{ note.title }}
            {% endfor %}
        </ul>
    </div>
{% endif %}
<div class=''>
    {{ section.text_end }}
</div>
<div class=''>
<button id='add-note'>Dodaj wpis</button>
</div>
<div class='new-note' hidden='true'>
    <form action="{% url 'report:note-list' section.id %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Dodaj wpis</button>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#add-note").click(function(){
            $("#add-note").attr('hidden', 'true')
            $(".new-note").toggle().removeAttr('hidden');
        });
    });
</script>
{% endblock %}

templates/report/notes2.html
{% extends "base.html" %}
{% block content %}

{% comment %} <div class=''>
    <h3>{{ section.title }}</h3>
</div> {% endcomment %}
<div class=''>
    <ul>
        {% for note in section.notes.all %}
            <li>{{ note.title }}
        {% endfor %}
    </ul>
</div>
<div class=''>
<button id='add-note'>Dodaj wpis</button>
</div>
<div class='new-note' hidden='true'>
    <form action="{% url 'report:note-list' section.id %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Dodaj wpis</button>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#add-note").click(function(){
            $("#add-note").attr('hidden', 'true')
            $(".new-note").toggle().removeAttr('hidden');
        });
    });
</script>
{% endblock %}

templates/report/report_contents_page.html
{% extends "base.html" %}
{% block content %}
<div class=''>
    <h1>Sprawozdanie mięsięczne ({{ report.year }}-{{ report.month }})</h1>
</div>
<div class=''>
<h3>Spis treści</h3>
<ol>
    {% for section in report.main_sections %}
        <li>{% include 'report/sections.html' with section=section %}
    {% endfor %}
</ol>
</div>
<div class=''>
    <li><a href="{% url 'report:add-section' %}">Dodaj sekcję</a></li>
</div>
{% endblock %}

templates/report/sections.html
{% comment %} {% if not section.section_master %}
    {{ section.title }}
{% else %} {% endcomment %}
    <a href="{% url 'report:note-list' section.id %}">{{ section.title }}</a>
{% comment %} {% endif %} {% endcomment %}
<ol>
    {% for subsection in section.subsections.all %}
        <li>{% include 'report/sections.html' with section=subsection %}</li>
    {% endfor %}
</ol>